### ISSUE TITLE
Unable to pass authentication credentials

### ISSUE THREAD

**Issue by seawitch4** [rdpatil4/ESClient#2]
When trying to connect to a basic-http auth'd elasticsearch cluster with http://user:password@host:port I get error: "Error connecting to:"

I can connect successfully using curl or REST api.

**Comment by seawitch4** [comment]
Yes, that works.  However, passing credentials in the URL works as well except when passing them through ESClient.  Just making you aware of the issue.

**Comment by derRobert** [comment]
I think, the config and .getJSON() methods would have to be extended to support auth. Like so:
```
  $.getJSON({
      'url': 'http://host.com/action/',
      'otherSettings': 'othervalues',
      'beforeSend': function(xhr) {
          //May need to use "Authorization" instead
          xhr.setRequestHeader("Authentication",
              "Basic " + encodeBase64(username + ":" + password)
      },
    success: function(result) {
        alert('done');
    }
});
```
