### ISSUE TITLE
Danger on deletes

### ISSUE THREAD

**Issue by necroscope** [rdpatil4/ESClient#5]
Hi,
I deleted data according to this search

EventDate: 2015-08-30 23*

It deleted everything in the index.  Yikes.  In kibana this same search only returned 48 records all the messages on 8/30.
However, in ESClient it deleted thousands of records.  So I am filing a bug with wildcard
deletes.  Every event had the EventDate field so they all got deleted despite being something like
EventDate: 2015-07

Thanks for your great work...this is not a complaint just want to make things better.  Seems a bug with wildcards *

**Comment by rdpatil4** [comment]
Hello,

I will investigate this, but I see problem in your query. I see there is space between "2015-08-30" and "23*". If you have not changed the default operator(OR), this Lucene query would be interpreted as EventDate:2015-08-30 OR _all:23*

Is this not what you intended?

**Comment by necroscope** [comment]
Hi,
I had it in quotes and unfortunately logstash puts the space in to signify it is the start of the
time so in the below 23 is the hour of the day or 11 pm.  I did not know a space 
signifies the "or" functionality.  Good to know.  Thanks for replying.

EventDate: "2015-08-30 23*"
