### ISSUE TITLE
Cross domain headers missing

### ISSUE THREAD

**Issue by lz1asl** [rdpatil4/ESClient#6]
I'm not able to use the latest version of the client after upgrading elasticsearch to 1.7.5 :

Chrome:
`XMLHttpRequest cannot load http://127.0.0.1:9200/_cluster/health. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://127.0.0.1:8443' is therefore not allowed access.`

Firefox:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9200/_cluster/health. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

Any way to workaround this?

**Comment by rdpatil4** [comment]
You would need to enable CORS for your elastic search instance. There is a note on the top on the github page for the same. Please check out. It will work after you do that change.
rdpatil4/ESClient

|   |
|   |  |   |   |   |   |   |
| rdpatil4/ESClientESClient - Elasticsearch client and web front end tool |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |

**Comment by lz1asl** [comment]
Thank you :)
